version: '2'
services:
  web:
    build: .
    environment:
      - HOST=0.0.0.0
    command: "npm run start"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
      - /usr/app/.nuxt
    ports:
      - "3000:3000"
